test_that("is_logicalish", {
  expect_true(is_logicalish(TRUE))
  expect_true(is_logicalish(FALSE))
  expect_true(is_logicalish(0L))
  expect_true(is_logicalish(1L))
  expect_true(is_logicalish(0.0))
  expect_true(is_logicalish(1.0))
  expect_true(is_logicalish(NA))
  expect_true(is_logicalish(c(1, 0, NA, NaN)))
  expect_true(is_logicalish(c(TRUE, FALSE, NA)))
  expect_true(is_logicalish(c(1.0, 0.0, NA, NaN)))

  expect_false(is_logicalish(0.5))
  expect_false(is_logicalish(-1))
  expect_false(is_logicalish(2))
  expect_false(is_logicalish(""))
  expect_false(is_logicalish("foo"))
  expect_false(is_logicalish(c(0, 0.5, 1)))
})
