# Generated by cpp11: do not edit by hand

antichain_ <- function(x) {
  .Call(`_nuggets_antichain_`, x)
}

dig_ <- function(logicals_data, doubles_data, logicals_foci, doubles_foci, configuration_list, fun) {
  .Call(`_nuggets_dig_`, logicals_data, doubles_data, logicals_foci, doubles_foci, configuration_list, fun)
}
