# Generated by cpp11: do not edit by hand

dig_ <- function(logicals_data, doubles_data, logicals_foci, doubles_foci, configuration_list, fun) {
  .Call(`_nuggets_dig_`, logicals_data, doubles_data, logicals_foci, doubles_foci, configuration_list, fun)
}
