#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom cli cli_abort
#' @importFrom DT datatable
#' @importFrom DT renderDT
#' @importFrom fastmatch fmatch
#' @importFrom generics explore
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 draw_key_point
#' @importFrom ggplot2 Geom
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_rect
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 GeomCurve
#' @importFrom ggplot2 GeomLabel
#' @importFrom ggplot2 GeomPoint
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggproto
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 layer
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 sec_axis
#' @importFrom grid gList
#' @importFrom htmltools div
#' @importFrom htmltools htmlEscape
#' @importFrom htmltools span
#' @importFrom htmltools tags
#' @importFrom lifecycle deprecated
#' @importFrom methods formalArgs
#' @importFrom purrr quietly
#' @importFrom purrr safely
#' @importFrom Rcpp sourceCpp
#' @importFrom rlang caller_arg
#' @importFrom rlang caller_env
#' @importFrom rlang current_env
#' @importFrom rlang enquo
#' @importFrom rlang enquos
#' @importFrom rlang is_integer
#' @importFrom rlang is_integerish
#' @importFrom rlang is_scalar_atomic
#' @importFrom rlang is_scalar_character
#' @importFrom rlang is_scalar_double
#' @importFrom rlang is_scalar_integerish
#' @importFrom rlang is_scalar_logical
#' @importFrom rlang quo_is_null
#' @importFrom rlang warn
#' @importFrom shiny actionButton
#' @importFrom shiny checkboxGroupInput
#' @importFrom shiny column
#' @importFrom shiny fluidRow
#' @importFrom shiny getDefaultReactiveDomain
#' @importFrom shiny icon
#' @importFrom shiny markdown
#' @importFrom shiny moduleServer
#' @importFrom shiny navbarPage
#' @importFrom shiny NS
#' @importFrom shiny observeEvent
#' @importFrom shiny plotOutput
#' @importFrom shiny radioButtons
#' @importFrom shiny reactive
#' @importFrom shiny renderPlot
#' @importFrom shiny renderTable
#' @importFrom shiny shinyApp
#' @importFrom shiny sliderInput
#' @importFrom shiny tableOutput
#' @importFrom shiny tabPanel
#' @importFrom shiny tabsetPanel
#' @importFrom shiny tagList
#' @importFrom shiny updateCheckboxGroupInput
#' @importFrom shiny updateRadioButtons
#' @importFrom shiny updateSliderInput
#' @importFrom shinyjs useShinyjs
#' @importFrom shinyWidgets alert
#' @importFrom shinyWidgets create_tree
#' @importFrom shinyWidgets panel
#' @importFrom shinyWidgets treeInput
#' @importFrom shinyWidgets updateTreeInput
#' @importFrom stats cor.test
#' @importFrom stats na.omit
#' @importFrom stats quantile
#' @importFrom stats setNames
#' @importFrom stats t.test
#' @importFrom stats var.test
#' @importFrom stats wilcox.test
#' @importFrom stringr str_trim
#' @importFrom tibble as_tibble
#' @importFrom tibble is_tibble
#' @importFrom tibble tibble
#' @importFrom tibble tribble
#' @importFrom tidyr expand_grid
#' @importFrom tidyselect eval_select
#' @importFrom tidyselect everything
#' @importFrom tidyselect where
#' @importFrom utils citation
#' @importFrom utils packageDescription
#' @useDynLib nuggets, .registration = TRUE
## usethis namespace: end
NULL

#' @export
generics::explore
