# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dig_ <- function(logicals_data, doubles_data, logicals_foci, doubles_foci, configuration_list, fun) {
    .Call(`_nuggets_dig_`, logicals_data, doubles_data, logicals_foci, doubles_foci, configuration_list, fun)
}

which_antichain_ <- function(x, dist) {
    .Call(`_nuggets_which_antichain_`, x, dist)
}

