# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dig_ <- function(logData, numData, logFoci, numFoci, confList) {
    .Call(`_nuggets_dig_`, logData, numData, logFoci, numFoci, confList)
}

raisedcos_ <- function(x, ctx) {
    .Call(`_nuggets_raisedcos_`, x, ctx)
}

triangle_ <- function(x, ctx) {
    .Call(`_nuggets_triangle_`, x, ctx)
}

which_antichain_ <- function(x, dist) {
    .Call(`_nuggets_which_antichain_`, x, dist)
}

