# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.goedel.tnorm <- function(vals) {
    .Call(`_nuggets_goedel_tnorm`, vals)
}

.pgoedel.tnorm <- function(list) {
    .Call(`_nuggets_pgoedel_tnorm`, list)
}

.lukas.tnorm <- function(vals) {
    .Call(`_nuggets_lukas_tnorm`, vals)
}

.plukas.tnorm <- function(list) {
    .Call(`_nuggets_plukas_tnorm`, list)
}

.goguen.tnorm <- function(vals) {
    .Call(`_nuggets_goguen_tnorm`, vals)
}

.pgoguen.tnorm <- function(list) {
    .Call(`_nuggets_pgoguen_tnorm`, list)
}

.goedel.tconorm <- function(vals) {
    .Call(`_nuggets_goedel_tconorm`, vals)
}

.pgoedel.tconorm <- function(list) {
    .Call(`_nuggets_pgoedel_tconorm`, list)
}

.lukas.tconorm <- function(vals) {
    .Call(`_nuggets_lukas_tconorm`, vals)
}

.plukas.tconorm <- function(list) {
    .Call(`_nuggets_plukas_tconorm`, list)
}

.goguen.tconorm <- function(vals) {
    .Call(`_nuggets_goguen_tconorm`, vals)
}

.pgoguen.tconorm <- function(list) {
    .Call(`_nuggets_pgoguen_tconorm`, list)
}

.goedel.residuum <- function(x, y) {
    .Call(`_nuggets_goedel_residuum`, x, y)
}

.lukas.residuum <- function(x, y) {
    .Call(`_nuggets_lukas_residuum`, x, y)
}

.goguen.residuum <- function(x, y) {
    .Call(`_nuggets_goguen_residuum`, x, y)
}

.invol.neg <- function(x) {
    .Call(`_nuggets_invol_neg`, x)
}

.strict.neg <- function(x) {
    .Call(`_nuggets_strict_neg`, x)
}

dig_ <- function(chains, namesVector, isCondition, isFocus, callback, confList) {
    .Call(`_nuggets_dig_`, chains, namesVector, isCondition, isFocus, callback, confList)
}

raisedcos_ <- function(x, ctx) {
    .Call(`_nuggets_raisedcos_`, x, ctx)
}

triangle_ <- function(x, ctx) {
    .Call(`_nuggets_triangle_`, x, ctx)
}

which_antichain_ <- function(x, dist) {
    .Call(`_nuggets_which_antichain_`, x, dist)
}

